<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<!--
      Everything under Expeditions is copied EXCEPT
      WPF XAML files and C# source files, which are
      handled automatically by the .NET SDK.
  -->
	<ItemGroup>
		<Content Include="Expeditions\**\*.*" Exclude="**\*.xaml;**\*.xaml.cs;**\*.cs">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="Expeditions\Safari\Assets\Waterfall\**" />
	  <Content Remove="Expeditions\Safari\Assets\Waterfall\**" />
	  <EmbeddedResource Remove="Expeditions\Safari\Assets\Waterfall\**" />
	  <None Remove="Expeditions\Safari\Assets\Waterfall\**" />
	  <Page Remove="Expeditions\Safari\Assets\Waterfall\**" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Expeditions\Safari\Waterfall\Effects\TestClass.cs" />
		<Compile Remove="Expeditions\Safari\Waterfall\WaterfallEffects.cs" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="Expeditions\Safari\Assets\Fire3\FireSlow.gif" />
		<Content Remove="Expeditions\Safari\Assets\Fire4\Flame1.png" />
		<Content Remove="Expeditions\Safari\Assets\Fire4\Flame10.png" />
		<Content Remove="Expeditions\Safari\Assets\images\SafariHeader.png" />
		
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controls\GuideCards\" />
		<Folder Include="Expeditions\Safari\Assets\Fire2\" />
		<Folder Include="Expeditions\Safari\Layouts\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MetadataExtractor" Version="2.9.3" />
		<PackageReference Include="TagLibSharp" Version="2.3.0" />
		<PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Expeditions\Safari\Assets\Fire3\FireSlow.gif" />
		<Resource Include="Expeditions\Safari\Assets\Fire4\Flame1.png" />
		<Resource Include="Expeditions\Safari\Assets\Fire4\Flame10.png" />
		<Resource Include="Expeditions\Safari\Assets\images\SafariHeader.png" />
		<Resource Include="Expeditions\Safari\Assets\Fire4\Smoke.png" />
	</ItemGroup>

</Project>